FROM node:20.8
# 作業ディレクトリの作成
RUN mkdir /my_webpack
WORKDIR /my_webpack
# COPY ./src/portal/package*.json ./
# COPY main.js ./
RUN npm init -y
#RUN npm install -D webpack webpack-cli
RUN npm install

#CMD ["npm", "run", "build"]